var svg = d3.select(".RATE_title")
    .append("svg")
    .attr('width', 1200)
    .attr('height', 75)
    .attr('transform','translate(180,0)')

    svg.append('text')
    .attr('x', 320)
    .attr('y', 70)
    .text('[ percentage of top5 crime types by year ]')
    .style('font-size', '23px')
    .attr("font-family", "sans-serif")
    .attr("font-weight", "bolder")
    .attr("fill", "black")
