var svg = d3.select(".YEAR_title")
    .append("svg")
    .attr('width', 1200)
    .attr('height', 75)
    .attr('transform','translate(180,0)')

    svg.append('text')
    .attr('x', 250)
    .attr('y', 60)
    .text('[ 범죄 유형 비율 ]')
    .style('font-size', '23px')
    .attr("font-family", "sans-serif")
    .attr("font-weight", "bolder")
    .attr("fill", "black")
